name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Test with coverage
      run: dotnet test --collect:"XPlat Code Coverage" --settings Tests/coverlet.runsettings
    - name: Copycat Action
      # You may pin to the exact commit or the version.
      # uses: andstor/copycat-action@c2b0316e9ab883478a4a7d40a4fcb03d17f281aa
      uses: andstor/copycat-action@v3.2.4
      with:
        # Personal access token
        personal_token: ${{ secrets.COPY }}
        # The source path to the file(s) or folder(s) to copy from
        src_path: Tests/TestResults/*/coverage.info
        dst_path: Tests/TestResults
        filter: /*/
        file_filter: "*.info"
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ github.token }}
        path-to-lcov: Tests/TestResults/coverage.info 
